stepback: false

# FUNCTIONS
functions:
  "fetchSource" :
    - command: git.get_project
      params:
        directory: "src"
  "debianSetup":
    command: shell.exec
    params:
      working_dir: "src"
      script: |
        set -o errexit
        set -o xtrace
        ./debian-setup.sh ${arch}
  "buildDebianLinuxToolchain":
    command: shell.exec
    params:
      working_dir: "src"
      script: |
        set -o errexit
        set -o xtrace
        ./build-debian-linux-toolchain.sh ${arch}
  "uploadToolchain":
    command: s3.put
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      local_file: src/php.tar.gz
      remote_file: ${aws_prefix}/${build_variant}/${revision}/${build_id}.tar.gz
      bucket: mciuploads
      permissions: public-read
      content_type: ${content_type|application/x-gzip}
  "pushToolchainRelease":
    command: s3Copy.copy
    params:
      aws_key: ${aws_key}
      aws_secret: ${aws_secret}
      s3_copy_files:
        - { 'source': { 'path': '${aws_prefix}/${build_variant}/${revision}/${build_id}.tar.gz', 'bucket': 'mciuploads' },
            'destination': { 'path': 'build/toolchain-drivers/mongo-php-driver/php-toolchain-${build_variant}-${revision}.tar.gz', 'bucket': 'boxes.10gen.com' }
          }

# PRE/POST TASKS
pre:
  - func: fetchSource

# TASK DEFINITIONS
tasks:
  - name: debian-setup
    commands:
      - func: debianSetup

  - name: build-debian-linux-toolchain
    depends_on:
    - name: debian-setup
    commands:
      - func: buildDebianLinuxToolchain
      - func: uploadToolchain

  - name: push-linux-binaries
    depends_on:
    - name: build-debian-linux-toolchain
    stepback: false
    commands:
      - func: pushToolchainRelease

# BUILD VARIANTS

buildvariants:

- name: debian92-64bit
  display_name: Debian 9.2 64-bit
  run_on:
    - debian92-build
  expansions:
    arch: 64bit
  tasks:
     - name: debian-setup
     - name: build-debian-linux-toolchain
     - name: push-linux-binaries

- name: debian92-32bit
  display_name: Debian 9.2 32-bit
  run_on:
    - debian92-build
  expansions:
    arch: 32bit
  tasks:
     - name: debian-setup
     - name: build-debian-linux-toolchain
     - name: push-linux-binaries

## OpenSSL 1.0.2
#- name: ubuntu1604
#  display_name: Ubuntu 16.04 x86_64
#  run_on:
#    - ubuntu1604-build
#  tasks:
#     - name: build-linux-toolchain
#     - name: push-linux-binaries
#
## OpenSSL 1.0.1
#- name: rhel62
#  display_name: RHEL 6.2 x86_64
#  run_on:
#    - rhel62-build
#  tasks:
#     - name: build-linux-toolchain
#     - name: push-linux-binaries
#
## PyMongo v2.9 distro
#- name: ubuntu1204
#  display_name: Ubuntu 12.04 x86_64
#  run_on:
#    - ubuntu1204-build
#  tasks:
#     - name: build-linux-toolchain
#     - name: push-linux-binaries
